In [2]:
# metin üretimi
# import libraries
# dataset
# preprocessing, tokenization, padding
# embedding
# # model

In [3]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense, LSTM

In [4]:
text = [
    "yemekler çok lezzetliydi", "servis çok hızlıydı", "atmosfer çok huzurlu", 
    "fiyatlar oldukça uygun", "personel çok güleryüzlü", "tekrar kesinlikle geleceğim", 
    "lezzet tam kıvamındaydı", "porsiyonlar gayet doyurucuydu", "tatlılar muazzamdı", 
    "mekan çok temizdi", "her şey kusursuzdu", "gerçekten çok beğendim", 
    "servis elemanları çok ilgiliydi", "ambiyans çok güzeldi", "manzara harikaydı", 
    "kaliteli bir hizmet aldık", "sunumlar çok şıktı", "lezzetine doyum olmaz", 
    "fiyat performans dengesi çok iyi", "çok keyifli bir akşam yemeğiydi", 
    "herkese tavsiye ederim", "taze malzemeler kullanılmış", "çok başarılı bir işletme", 
    "hızlı ve sıcak servis", "çok memnun kaldık", "lezzetli başlangıçlar", 
    "mükemmel servis", "taze ekmekler", "ilgili personel", "hoş bir deneyim", 
    "süper bir yer", "kaliteli hizmet", "fiyatlar gayet iyi", "lezzet durağı", 
    "harika tatlar", "çok mutlu ayrıldım", "hızlı ve sıcak", "güzel bir akşam yemeği", 
    "her şey taze", "harika atmosfer", "çok beğendik", "servis çok iyi", 
    "kesinlikle tekrar gelirim", "leziz yemekler", "harika deneyim", "çok kaliteli", 
    "gerçekten beğendim", "güler yüzlü karşılama", "ferah bir yer", "lezzeti tam yerinde", 
    "yemekler çok soğuktu", "servis aşırı yavaştı", "fiyatlar çok pahalı", 
    "personel çok kaba davrandı", "mekan çok pisti", "yemekler hiç taze değildi", 
    "porsiyonlar çok küçüktü", "bir daha asla gelmem", "tam bir hayal kırıklığıydı", 
    "sunumlar çok özensizdi", "gürültüden konuşamadık", "beklediğim lezzeti bulamadım", 
    "masalar çok kirliydi", "çok uzun süre bekledik", "yemekler çok yağlıydı", 
    "müşteri ile hiç ilgilenmediler", "fiyatlar kalitesine göre çok yüksek", 
    "içerisi çok havasızdı", "yanlış sipariş getirdiler", "porsiyonlar hiç doyurucu değildi", 
    "lezzet çok sıradandı", "garsonlar çok ilgisizdi", "hiç memnun kalmadım", 
    "çok kötü bir deneyimdi", "ortam çok rahatsız ediciydi", "yemek çok tuzlu", 
    "beklediğim gibi değil", "hijyenik değil", "çalışanlar umursamaz", "çok kalabalık", 
    "fiyatı hak etmiyor", "servis gecikti", "lezzeti kötü", "rahatsız edici ortam", 
    "çok geç geldi", "hiç memnun kalmadım", "hizmet kötü", "kalite düşük", 
    "yemekler bayat", "çok soğuktu", "ilgilenmediler", "gereksiz pahalı", 
    "yerler kirliydi", "çok ses vardı", "özensiz hazırlanmış", "yavaş servis", 
    "hiç taze değildi", "kötü kokuyordu", "beklentinin altında", "pişman oldum"
]

In [8]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(text)
total_word=len(tokenizer.word_index)+1
print("Toplam Kelime Sayısı: ", total_word)

input_sequences=[]
for line in text:
    token_list=tokenizer.texts_to_sequences([line])[0]

    for i in range(1, len(token_list)):
        n_gram_sequence=token_list[:i+1]
        input_sequences.append(n_gram_sequence)

print("Toplam Cümle Sayısı: ", len(input_sequences))

Toplam Kelime Sayısı:  168
Toplam Cümle Sayısı:  186


In [12]:
max_sequence_length=max([len(x) for x in input_sequences])
print("Maksimum Cümle Uzunluğu: ", max_sequence_length)

input_sequences=pad_sequences(input_sequences, maxlen=max_sequence_length, padding="pre")
print("Padded Cümleler: \n", input_sequences)

Maksimum Cümle Uzunluğu:  5
Padded Cümleler: 
 [[  0   0   0   4   1]
 [  0   0   4   1  45]
 [  0   0   0   3   1]
 [  0   0   3   1  46]
 [  0   0   0  20   1]
 [  0   0  20   1  47]
 [  0   0   0   7  48]
 [  0   0   7  48  49]
 [  0   0   0   9   1]
 [  0   0   9   1  50]
 [  0   0   0  21  22]
 [  0   0  21  22  51]
 [  0   0   0  10  11]
 [  0   0  10  11  52]
 [  0   0   0  12  23]
 [  0   0  12  23  53]
 [  0   0   0  54  55]
 [  0   0   0  24   1]
 [  0   0  24   1  56]
 [  0   0   0  25  26]
 [  0   0  25  26  57]
 [  0   0   0  27   1]
 [  0   0  27   1  28]
 [  0   0   0   3  58]
 [  0   0   3  58   1]
 [  0   3  58   1  59]
 [  0   0   0  60   1]
 [  0   0  60   1  61]
 [  0   0   0  62  63]
 [  0   0   0  13   2]
 [  0   0  13   2  14]
 [  0  13   2  14  64]
 [  0   0   0  29   1]
 [  0   0  29   1  65]
 [  0   0   0  66  67]
 [  0   0  66  67  68]
 [  0   0   0  69  70]
 [  0   0  69  70  71]
 [  0  69  70  71   1]
 [ 69  70  71   1  15]
 [  0   0   0   1  72]
 [  0   0 

In [14]:
X=input_sequences[:,:-1]
y=input_sequences[:,-1]

y=tf.keras.utils.to_categorical(y, num_classes=total_word)


In [15]:
model=Sequential()

model.add(Embedding(input_dim=total_word, output_dim=100, input_length=max_sequence_length-1))

model.add(LSTM(100, return_sequences=False))

model.add(Dense(total_word, activation="softmax"))
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])
model.fit(X, y, epochs=100, batch_size=32)



Epoch 1/100


c:\Users\kadir\OneDrive\Masaüstü\teknofest_saglıkt_YZ\pull_the_dataset\.venv\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.0753 - loss: 5.1210
Epoch 2/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1344 - loss: 5.0990 
Epoch 3/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1344 - loss: 5.0595 
Epoch 4/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1344 - loss: 4.9750 
Epoch 5/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1344 - loss: 4.7431 
Epoch 6/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1344 - loss: 4.6083 
Epoch 7/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1344 - loss: 4.5278 
Epoch 8/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1344 - loss: 4.4746 
Epoch 9/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1344 - loss: 4.4518 
Epoch 10/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1398 - loss: 4.4141 
Epoch 11/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1398 - loss: 4.3940 
Epoch 12/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1344 - loss: 4.3703 
Ep

In [19]:
def generate_text(seed_text, next_words):
    for _ in range(next_words):
        token_list=tokenizer.texts_to_sequences([seed_text])[0]
        token_list=pad_sequences([token_list], maxlen=max_sequence_length-1, padding="pre")
        predicted=model.predict(token_list, verbose=0)
        predicted_word_index=np.argmax(predicted, axis=-1)[0]

        predicted_word=tokenizer.index_word[predicted_word_index]
        
        seed_text += " " + predicted_word
    
    return seed_text

seed_text="yemek"
generated_text=generate_text(seed_text, next_words=2)
print(generated_text)



yemek çok tuzlu
