In [ ]:
# import librarys
# dataset
# metin temizleme, tokenizasyon, stop word kaldırma, lemmatization
# metin temsili
# mdeolling



In [2]:
import pandas as pd
import numpy as np

!pip install keras
!pip install tensorflow
from gensim.models import Word2Vec
from keras.models import Sequential
from keras.layers import SimpleRNN,Dense, LSTM, Embedding
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

In [10]:
data = {
    "text": [
        "yemekler çok lezzetliydi", "servis çok hızlıydı", "atmosfer çok huzurlu", 
        "fiyatlar oldukça uygun", "personel çok güleryüzlü", "tekrar kesinlikle geleceğim", 
        "lezzet tam kıvamındaydı", "porsiyonlar gayet doyurucuydu", "tatlılar muazzamdı", 
        "mekan çok temizdi", "her şey kusursuzdu", "gerçekten çok beğendim", 
        "servis elemanları çok ilgiliydi", "ambiyans çok güzeldi", "manzara harikaydı", 
        "kaliteli bir hizmet aldık", "sunumlar çok şıktı", "lezzetine doyum olmaz", 
        "fiyat performans dengesi çok iyi", "çok keyifli bir akşam yemeğiydi", 
        "herkese tavsiye ederim", "taze malzemeler kullanılmış", "çok başarılı bir işletme", 
        "hızlı ve sıcak servis", "çok memnun kaldık", "yemekler çok soğuktu", 
        "servis aşırı yavaştı", "fiyatlar çok pahalı", "personel çok kaba davrandı", 
        "mekan çok pisti", "yemekler hiç taze değildi", "porsiyonlar çok küçüktü", 
        "bir daha asla gelmem", "tam bir hayal kırıklığıydı", "sunumlar çok özensizdi", 
        "gürültüden konuşamadık", "beklediğim lezzeti bulamadım", "masalar çok kirliydi", 
        "çok uzun süre bekledik", "yemekler çok yağlıydı", "müşteri ile hiç ilgilenmediler", 
        "fiyatlar kalitesine göre çok yüksek", "içerisi çok havasızdı", "yanlış sipariş getirdiler", 
        "porsiyonlar hiç doyurucu değildi", "lezzet çok sıradandı", "garsonlar çok ilgisizdi", 
        "hiç memnun kalmadım", "çok kötü bir deneyimdi", "ortam çok rahatsız ediciydi"
    ],
    "label": [
        "pozitif", "pozitif", "pozitif", "pozitif", "pozitif", "pozitif", "pozitif", 
        "pozitif", "pozitif", "pozitif", "pozitif", "pozitif", "pozitif", "pozitif", 
        "pozitif", "pozitif", "pozitif", "pozitif", "pozitif", "pozitif", "pozitif", 
        "pozitif", "pozitif", "pozitif", "pozitif", "negatif", "negatif", "negatif", 
        "negatif", "negatif", "negatif", "negatif", "negatif", "negatif", "negatif", 
        "negatif", "negatif", "negatif", "negatif", "negatif", "negatif", "negatif", 
        "negatif", "negatif", "negatif", "negatif", "negatif", "negatif", "negatif", "negatif"
    ]
}

In [11]:
df=pd.DataFrame(data)

In [12]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(df["text"])
sequances=tokenizer.texts_to_sequences(df["text"])
word_index=tokenizer.word_index
print("sequances: ", sequances)
print("kelime indeksi: ", word_index)


sequances:  [[3, 1, 16], [4, 1, 17], [18, 1, 19], [6, 20, 21], [8, 1, 22], [23, 24, 25], [9, 10, 26], [7, 27, 28], [29, 30], [11, 1, 31], [32, 33, 34], [35, 1, 36], [4, 37, 1, 38], [39, 1, 40], [41, 42], [43, 2, 44, 45], [12, 1, 46], [47, 48, 49], [50, 51, 52, 1, 53], [1, 54, 2, 55, 56], [57, 58, 59], [13, 60, 61], [1, 62, 2, 63], [64, 65, 66, 4], [1, 14, 67], [3, 1, 68], [4, 69, 70], [6, 1, 71], [8, 1, 72, 73], [11, 1, 74], [3, 5, 13, 15], [7, 1, 75], [2, 76, 77, 78], [10, 2, 79, 80], [12, 1, 81], [82, 83], [84, 85, 86], [87, 1, 88], [1, 89, 90, 91], [3, 1, 92], [93, 94, 5, 95], [6, 96, 97, 1, 98], [99, 1, 100], [101, 102, 103], [7, 5, 104, 15], [9, 1, 105], [106, 1, 107], [5, 14, 108], [1, 109, 2, 110], [111, 1, 112, 113]]
kelime indeksi:  {'çok': 1, 'bir': 2, 'yemekler': 3, 'servis': 4, 'hiç': 5, 'fiyatlar': 6, 'porsiyonlar': 7, 'personel': 8, 'lezzet': 9, 'tam': 10, 'mekan': 11, 'sunumlar': 12, 'taze': 13, 'memnun': 14, 'değildi': 15, 'lezzetliydi': 16, 'hızlıydı': 17, 'atmosfer': 

In [13]:
maxlen=max(len(x) for x in sequances)
X= pad_sequences(sequances, maxlen=maxlen)
print("padded sequances: \n", X)

padded sequances: 
 [[  0   0   3   1  16]
 [  0   0   4   1  17]
 [  0   0  18   1  19]
 [  0   0   6  20  21]
 [  0   0   8   1  22]
 [  0   0  23  24  25]
 [  0   0   9  10  26]
 [  0   0   7  27  28]
 [  0   0   0  29  30]
 [  0   0  11   1  31]
 [  0   0  32  33  34]
 [  0   0  35   1  36]
 [  0   4  37   1  38]
 [  0   0  39   1  40]
 [  0   0   0  41  42]
 [  0  43   2  44  45]
 [  0   0  12   1  46]
 [  0   0  47  48  49]
 [ 50  51  52   1  53]
 [  1  54   2  55  56]
 [  0   0  57  58  59]
 [  0   0  13  60  61]
 [  0   1  62   2  63]
 [  0  64  65  66   4]
 [  0   0   1  14  67]
 [  0   0   3   1  68]
 [  0   0   4  69  70]
 [  0   0   6   1  71]
 [  0   8   1  72  73]
 [  0   0  11   1  74]
 [  0   3   5  13  15]
 [  0   0   7   1  75]
 [  0   2  76  77  78]
 [  0  10   2  79  80]
 [  0   0  12   1  81]
 [  0   0   0  82  83]
 [  0   0  84  85  86]
 [  0   0  87   1  88]
 [  0   1  89  90  91]
 [  0   0   3   1  92]
 [  0  93  94   5  95]
 [  6  96  97   1  98]
 [  0   0  99 

In [14]:
label_encoder=LabelEncoder()
y=label_encoder.fit_transform(df["label"])
print("encoded labels: ", y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

encoded labels:  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [16]:
senteces=[text.split() for text in df["text"]]
word2vec_model=Word2Vec(sentences=senteces, vector_size=100, window=5, min_count=1, workers=4)
embeding_dim=100
embeding_matrix=np.zeros((len(word_index)+1, embeding_dim))
for word, i in word_index.items():
    if word in word2vec_model.wv:
        embeding_matrix[i]=word2vec_model.wv[word]

print("embedding matrix: \n", embeding_matrix)

embedding matrix: 
 [[ 0.          0.          0.         ...  0.          0.
   0.        ]
 [-0.00054066  0.0002703   0.00515419 ... -0.00712693  0.00092483
   0.00637731]
 [-0.00862819  0.00367242  0.00521589 ... -0.00243713 -0.00950946
   0.00450398]
 ...
 [ 0.00180023  0.00704609  0.0029447  ... -0.00185955  0.00361175
  -0.00703643]
 [ 0.00130016 -0.00980214  0.00459432 ... -0.002587   -0.00775514
   0.00419399]
 [-0.00719224  0.00423121  0.00216817 ...  0.00943308  0.00706113
   0.00675335]]


In [17]:
model=Sequential()
model.add(Embedding(input_dim=len(word_index)+1, output_dim=embeding_dim, weights=[embeding_matrix], input_length=maxlen, trainable=False))
model.add(SimpleRNN(128, return_sequences=False))
model.add(Dense(1, activation="sigmoid"))
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

test_loss, test_acc = model.evaluate(X_test, y_test)
print("Test Loss: ", test_loss)
print("Test Accuracy: ", test_acc)

Epoch 1/10


c:\Users\kadir\OneDrive\Masaüstü\teknofest_saglıkt_YZ\pull_the_dataset\.venv\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 229ms/step - accuracy: 0.2750 - loss: 0.6974 - val_accuracy: 0.7000 - val_loss: 0.6913
Epoch 2/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.4750 - loss: 0.6920 - val_accuracy: 0.4000 - val_loss: 0.6986
Epoch 3/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6000 - loss: 0.6882 - val_accuracy: 0.3000 - val_loss: 0.7061
Epoch 4/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5750 - loss: 0.6856 - val_accuracy: 0.3000 - val_loss: 0.7135
Epoch 5/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5500 - loss: 0.6812 - val_accuracy: 0.3000 - val_loss: 0.7199
Epoch 6/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5500 - loss: 0.6780 - val_accuracy: 0.3000 - val_loss: 0.7302
Epoch 7/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5500 - loss: 0.6735 - val_accuracy: 0.3000 - val_loss: 0.7456
Epoch 8/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5500 - loss: 0.6744 - val_accuracy: 0.3000 - val_loss: 0.7583
Epoch 9/10

In [20]:
# cümle sınıflandırması 
def classify_sentence(sentence):
    seq=tokenizer.texts_to_sequences([sentence])
    padded_seq=pad_sequences(seq, maxlen=maxlen)

    predict=model.predict(padded_seq)

    predict_class=(predict > 0.5).astype(int)
    print("Predicted class: ", predict_class)
    print("Predicted label: ", label_encoder.inverse_transform(predict_class)[0])

    return predict_class

sentence="yemekler çok lezzetliydi"
predicted_class=classify_sentence(sentence)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
Predicted class:  [[1]]
Predicted label:  pozitif


c:\Users\kadir\OneDrive\Masaüstü\teknofest_saglıkt_YZ\pull_the_dataset\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:161: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
