In [25]:
# import libraries
# veri seti yükle
# metin temizle
# vectorizer oluştur
# metin veri setini sayıllaştır
# kelime küöesi
# vektor temsili
# kelim efrekansı

In [38]:
# =========================================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import CountVectorizer
import re
from collections import Counter


In [39]:
import zipfile

zip_yolu = "IMBD.csv.zip"
hedef_klasor = "IMBD.csv"

# Zip dosyasını okuma modunda ('r') açıyoruz
with zipfile.ZipFile(zip_yolu, 'r') as zip_ref:
    # Tüm içeriği hedef klasöre çıkarıyoruz
    zip_ref.extractall(hedef_klasor)

print("Dosyalar başarıyla çıkarıldı.")

Dosyalar başarıyla çıkarıldı.


In [40]:
# =========================================================
# 2. LOAD DATASET
# =========================================================
data_path = "C:\\Users\\kadir\\OneDrive\\Masaüstü\\llm\\IMBD.csv\\IMBD.csv"
df = pd.read_csv(data_path)
documents=df["description"]

df.head()

,title,year,certificate,duration,genre,rating,description,stars,votes
0,Cobra Kai,(2018– ),TV-14,30 min,"Action, Comedy, Drama",8.5,Decades after their 1984 All Valley Karate Tou...,"['Ralph Macchio, ', 'William Zabka, ', 'Courtn...","177,031"
1,The Crown,(2016– ),TV-MA,58 min,"Biography, Drama, History",8.7,Follows the political rivalries and romance of...,"['Claire Foy, ', 'Olivia Colman, ', 'Imelda St...","199,885"
2,Better Call Saul,(2015–2022),TV-MA,46 min,"Crime, Drama",8.9,The trials and tribulations of criminal lawyer...,"['Bob Odenkirk, ', 'Rhea Seehorn, ', 'Jonathan...","501,384"
3,Devil in Ohio,(2022),TV-MA,356 min,"Drama, Horror, Mystery",5.9,When a psychiatrist shelters a mysterious cult...,"['Emily Deschanel, ', 'Sam Jaeger, ', 'Gerardo...","9,773"
4,Cyberpunk: Edgerunners,(2022– ),TV-MA,24 min,"Animation, Action, Adventure",8.6,A Street Kid trying to survive in a technology...,"['Zach Aguilar, ', 'Kenichiro Ohashi, ', 'Emi ...","15,413"


In [41]:
!pip install nltk
import nltk
from nltk.corpus import stopwords
nltk.download("stopwords")
stop_words=set(stopwords.words("english"))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\kadir\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
def clean_text(text):
    # büyük küçük harf dönüşümü
    text=text.lower()
    # rakamların temizlenmesi
    text=re.sub(r"\d+","",text)
    # noktalama işaretlerinin temizlenmesi
    text=re.sub(r"\W\s","",text)
    # kısa kelimelerin temizlenmesi
    cleaned_doc=[word for word in cleaned_doc if word not in stop_words and len(word)>2]
    return text

cleaned_doc=[clean_text(doc) for doc in documents]


In [45]:
vectorizer=CountVectorizer()
X=vectorizer.fit_transform(cleaned_doc[:75])

In [46]:
feature_names=vectorizer.get_feature_names_out()
print(f"feature names: {feature_names}")

feature names: ['abilitythwart' 'aboard' 'about' 'accept' 'accidentally' 'across'
 'action' 'activities' 'adaptation' 'addamsyears' 'adjusts' 'adrift'
 'adultsbut' 'advisor' 'affairs' 'after' 'again' 'against' 'agatha' 'aged'
 'agency' 'agent' 'agree' 'airliner' 'alfred' 'alive' 'all' 'also'
 'america' 'american' 'amerie' 'among' 'ancestral' 'and' 'angeles'
 'angels' 'animated' 'another' 'anthology' 'apart' 'apartmust'
 'apocalypsea' 'apologies' 'appear' 'appease' 'approach' 'aragorn' 'are'
 'army' 'around' 'arrest' 'arrival' 'arrivesfollow' 'artist' 'arts'
 'aspiring' 'assassins' 'asset' 'asyluma' 'attempts' 'aubrey' 'awaits'
 'away' 'awayhe' 'back' 'badbrilliant' 'balance' 'band' 'battle' 'beach'
 'beasts' 'become' 'becomes' 'becoming' 'bee' 'beean' 'before' 'begins'
 'being' 'beings' 'beneath' 'benoit' 'best' 'better' 'between' 'billion'
 'birthright' 'blades' 'blanc' 'bleak' 'blind' 'bloom' 'body' 'bookedand'
 'born' 'boss' 'bounty' 'bouta' 'boy' 'breakuponly' 'brenda' 'bright'
 'b

In [47]:
vektor_temsili=X.toarray()
print("vektör temsili:\n",vektor_temsili)

vektör temsili:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [48]:
words_counts=X.sum(axis=0).A1
word_freq=dict(zip(feature_names,words_counts))
print("kelime frekansı:\n",word_freq)

kelime frekansı:
 {'abilitythwart': np.int64(1), 'aboard': np.int64(2), 'about': np.int64(1), 'accept': np.int64(1), 'accidentally': np.int64(1), 'across': np.int64(1), 'action': np.int64(2), 'activities': np.int64(1), 'adaptation': np.int64(1), 'addamsyears': np.int64(1), 'adjusts': np.int64(1), 'adrift': np.int64(1), 'adultsbut': np.int64(1), 'advisor': np.int64(1), 'affairs': np.int64(1), 'after': np.int64(9), 'again': np.int64(2), 'against': np.int64(1), 'agatha': np.int64(1), 'aged': np.int64(1), 'agency': np.int64(1), 'agent': np.int64(1), 'agree': np.int64(1), 'airliner': np.int64(1), 'alfred': np.int64(1), 'alive': np.int64(2), 'all': np.int64(1), 'also': np.int64(1), 'america': np.int64(1), 'american': np.int64(1), 'amerie': np.int64(1), 'among': np.int64(1), 'ancestral': np.int64(2), 'and': np.int64(61), 'angeles': np.int64(2), 'angels': np.int64(1), 'animated': np.int64(1), 'another': np.int64(3), 'anthology': np.int64(2), 'apart': np.int64(1), 'apartmust': np.int64(1), 'apo

In [35]:
most_common_words=Counter(word_freq).most_common(10)
print("en sık kullanılan kelimeler:\n",most_common_words)

en sık kullanılan kelimeler:
 [('the', np.int64(69)), ('and', np.int64(61)), ('his', np.int64(24)), ('her', np.int64(15)), ('their', np.int64(15)), ('with', np.int64(15)), ('for', np.int64(12)), ('new', np.int64(12)), ('family', np.int64(11)), ('from', np.int64(11))]
